// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://fegvrjnhdqmydfruadrx.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImZlZ3Zyam5oZHFteWRmcnVhZHJ4Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDMxNTE2ODMsImV4cCI6MjA1ODcyNzY4M30.pj_fFI8giz6gyR3M9Mwmp6hmfMNWpENNIsy-EhQEesM";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);